package com.hapticapps.amici.shared.data_models.org;
// Generated by mdo do not edit this file, see the .mdo file 

import com.hapticapps.amici.shared.utils.Utils;
import org.bson.codecs.pojo.annotations.BsonProperty;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import com.mongodb.client.model.IndexOptions;
import org.bson.conversions.Bson;
import com.mongodb.BasicDBObject;

public class OrgPerson {
	public static final String BSON_UUID = "u";
	public static final String BSON_ORGID = "o";
	public static final String BSON_NAME = "n";
	public static final String BSON_EMAIL = "e";

	@BsonProperty("u")
	private String uuid = Utils.newUID();

	@BsonProperty("o")
	private String orgId;

	@BsonProperty("n")
	private String name;

	@BsonProperty("e")
	private String email;


	public String getUuid(){
		return uuid;
	}
	public void setUuid(String data){
		this.uuid = data;
	}
	public String getOrgId(){
		return orgId;
	}
	public void setOrgId(String data){
		this.orgId = data;
	}
	public String getName(){
		return name;
	}
	public void setName(String data){
		this.name = data;
	}
	public String getEmail(){
		return email;
	}
	public void setEmail(String data){
		this.email = data;
	}

	public OrgPersonBuilder copy() {
		return OrgPersonBuilder.from( this );
	}

	public static OrgPersonBuilder builder() {
		return new OrgPersonBuilder();
	}
	public String toString() {
		return "OrgPerson{" + 
		"}";
	}

	public static class OrgPersonBuilder {

		private String uuid = Utils.newUID();

		private String orgId;

		private String name;

		private String email;

		public static OrgPersonBuilder from(OrgPerson source) {
			var r = new OrgPersonBuilder();
			r.uuid = source.getUuid();
			r.orgId = source.getOrgId();
			r.name = source.getName();
			r.email = source.getEmail();
			return r;
		}

		public OrgPersonBuilder withUuid(String uuid) {
			this.uuid = uuid;
			return this;
		}

		public OrgPersonBuilder withOrgId(String orgId) {
			this.orgId = orgId;
			return this;
		}

		public OrgPersonBuilder withName(String name) {
			this.name = name;
			return this;
		}

		public OrgPersonBuilder withEmail(String email) {
			this.email = email;
			return this;
		}

		public OrgPerson build() {
			var r = new OrgPerson();
			r.uuid = uuid;
			r.orgId = orgId;
			r.name = name;
			r.email = email;
			return r;
		}
	}
	public static class Indexes {
		public static List<Bson> ikeys = new ArrayList<>();
		public static List<IndexOptions> ioptions = new ArrayList<>();
		static {
		}
	}
}

